namespace: wildfly
name: jcliff
version: 0.0.3
readme: README.md
authors:
  - Romain Pelisse <belaran@redhat.com>
  - Andrew Block <ablock@redhat.com>
description: Provides integration with JCliff to enable Ansible to provisioning JBoss EAP or Wildfly instances.
license_file: "LICENSE"
tags:
  - java
  - jboss
  - wildfly
  - cli
  - server
dependencies: {}
repository: https://github.com/wildfly-extras/ansible_collections_jcliff
documentation: https://github.com/wildfly-extras/ansible_collections_jcliff
homepage: https://github.com/wildfly-extras/ansible_collections_jcliff
issues: https://github.com/wildfly-extras/ansible_collections_jcliff/issues
