namespace: middleware_automation
name: jcliff
version: "0.0.23"
readme: README.md
authors:
  - Romain Pelisse <belaran@redhat.com>
  - Andrew Block <ablock@redhat.com>
  - Harsha Cherukuri <hcheruku@redhat.com>
description: Provides integration with JCliff to enable Ansible to provisioning JBoss EAP or Wildfly instances.
license_file: "LICENSE"
tags:
  - java
  - jboss
  - wildfly
  - cli
  - server
dependencies:
  middleware_automation.wildfly: '>=1.0.0'
repository: https://github.com/ansible-middleware/ansible_collections_jcliff
documentation: https://github.com/ansible-middleware/ansible_collections_jcliff
homepage: https://github.com/ansible-middleware/ansible_collections_jcliff
issues: https://github.com/ansible-middleware/ansible_collections_jcliff/issues
build_ignore:
  - molecule
  - .github
  - '*.tar.gz'
  - '*.zip'
  - changelogs/fragments/.gitignore