---
- name: Converge
  hosts: all
  vars_files:
    - vars/main.yml
  vars:
    app: /tmp/simple-webapp.war
    gdrive_url: 'https://drive.google.com/uc?export=download&id='
    app_url: "{{ gdrive_url }}1w9ss5okctnjUvRAxhPEPyC7DmbUwmbhb"
  collections:
    - middleware_automation.wildfly
    - middleware_automation.jcliff
  tasks:

    - include_role:
        name: wildfly_install
    - include_role:
        name: wildfly_systemd

    - include_role:
        name: ../../roles/jcliff

    - name: "Download a demo app to deploy"
      get_url:
        url: "{{ app_url }}"
        dest: "{{ app }}"

    - wait_for:
        port: 8080

    - include_role:
        name: wildfly_driver
      vars:
        wildfly_user: wildfly
        jdbc_driver_module_dir: "{{ wildfly_home }}//modules/org/postgresql/main"
        jdbc_driver_version: 9.2-1002-jdbc4
        jdbc_driver_jar_filename: "postgresql-{{ jdbc_driver_version }}.jar"
        jdbc_driver_jar_url: "https://repo.maven.apache.org/maven2/org/postgresql/postgresql/{{ jdbc_driver_version }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_module_name: "org.postgresql"

    - jcliff:
        wfly_home: "{{ wildfly_home }}"
        timeout: 60000
        components:
          - system_properties:
              - name: jcliff.enabled
                value: "enabled.plus"
          - deployments:
              - name: simple-webapp
                runtime_name: simple-webapp-v1.war
                path: /tmp/simple-webapp.war
          - drivers:
              - driver_name: postgresql
                driver_module_name: org.postgresql
                driver_class_name: org.postgresql.Driver
                driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
          - datasources:
              - name: ExampleDS2
                use_java_context: "true"
                jndi_name: java:jboss/datasources/ExampleDS2
                connection_url: "jdbc:h2:mem:test2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
                driver_name: h2
#Seems that activemq is broken with WFLY26, to double-check
#          - messaging_activemq:
#              jms_queue:
#                - name: myQueue
#                  entries:
#                    [
#                      "queue/myQueue",
#                      "jms/queue/myQueue",
#                      "java:jboss/exported/jms/queue/myQueue",
#                    ]
#              jms_topic:
#                - name: myTopic
#                  entries: ["MyTopic"]
