---
- name: Converge
  hosts: all
  vars_files:
    - vars/main.yml
  vars:
    app_url: http://people.redhat.com/~rpelisse/simple-webapp.war
    app: /tmp/simple-webapp.war
  collections:
    - wildfly.jcliff
  roles:
    - jcliff
  tasks:
    - name: "Download a demo app to deploy"
      get_url:
        url: "{{ app_url }}"
        dest: "{{ app }}"

    - jcliff:
        wfly_home: "{{ wildfly.home }}"
        components:
          system_property:
            "jcliff.enabled": "enabled.plus"
          deployments:
            "simple-webapp":
              name: "simple-webapp"
              RUNTIME-NAME: simple-webapp-v1.war
              path: /tmp/simple-webapp.war
          datasource:
            "ExampleDS2":
              use_java_context: "true"
              jndi_name: java:jboss/datasources/ExampleDS2
              connection_url: "jdbc:h2:mem:test2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
              driver_name: h2
