---
wfly_version: 18.0.1.Final
workdir: /opt/wildfly/
wfly_zipfile: "wildfly-{{ wfly_version }}.zip"
wfly_download_url: https://download.jboss.org/wildfly/{{ wfly_version }}/{{ wfly_zipfile }}
wildfly:
  home: "{{ workdir }}/wildfly-{{ wfly_version }}/"
  user: wildfly
  min_mem: 64m
  max_mem: 512m
  metaspace_size: 96m
  metaspace_maxsize: 256m
pgsql_module_dir: "{{ wildfly.home }}//modules/org/postgresql/main"
jdbc_driver_filename: postgresql-9.2-1002-jdbc4.jar
jdbc_driver_url: https://repo.maven.apache.org/maven2/org/postgresql/postgresql/9.2-1002-jdbc4/{{ jdbc_driver_filename }}
jdbc_driver_path: "{{ pgsql_module_dir }}/{{ jdbc_driver_filename }}"
