---

- name: Collect Supported Operating Systems
  set_fact:
    jcliff_install_supported_os: "{{ ( jcliff_install_supported_os | default([]) ) + item.value }}"
  loop: "{{ lookup('dict', jcliff_install_matrix) }}"


- name: Install JCliff using package managers
  block:
    - name: Verify supported Operating Systems
      assert:
        that:
          - ansible_distribution is not undefined
          - ansible_distribution in jcliff_install_supported_os or ansible_os_family in jcliff_install_supported_os
        fail_msg: "Unsupported Operating system for package installation"
        quiet: true

    - name: Install JCliff using Chocolatey
      include_tasks: install_chocolatey.yml
      when: ansible_distribution in jcliff_install_matrix.chocolatey or ansible_os_family in jcliff_install_matrix.chocolatey

- name: Install Jcliff using standalone binary
  include_tasks: install_standalone.yml
  when: jcliff_standalone | bool == true
